### ISSUE TITLE
No used/free stats shown on M1

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/disk_report#12]
The storage page for MBA with default setup shows 8 volumes but no Used/Free stats for any of them. This only affects M1 models, Intel models with BigSur are OK.

**Comment by ofirgalcon** [comment]
The stats are shown correctly in listing but not in client tab

**Comment by tuxudo** [comment]
Should be resolved with PR #21

**Comment by ofirgalcon** [comment]
I just tried and still getting the same results. I got the python version here: https://github.com/MagerValp/MunkiReport-Python/releases/tag/v3.10.2

**Comment by tuxudo** [comment]
Added more volumes to exclude. Thank you for the update

**Comment by tuxudo** [comment]
Resolved with version v4.1 of the module
